# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVEuoDG-CprMBymkj53kiUqUssLFXx0u
"""

import pandas as pd
import seaborn as sns
path="/content/Accident acc.csv"
df = pd.read_csv(path)
df.head()

import pandas as pd

df = pd.read_csv(path)

data=df.loc[:,['Vehicle spped','Accident severity']]

data.head()

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv(path)
df.plot(x='Accident severity', y='Vehicle spped', style='o')
plt.xlabel('Accident severity')
plt.ylabel('Vehicle spped')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import numpy as np

# Load the dataset
df = pd.read_csv(path)

# Reshape data for regression model (X needs to be 2D for sklearn's LinearRegression)
X = df[['Accident severity']].values
y = df['Vehicle spped'].values

# Fit the linear regression model
model = LinearRegression()
model.fit(X, y)

# Predict values to draw the regression line
y_pred = model.predict(X)

# Plot the data points
plt.scatter(df['Accident severity'], df['Vehicle spped'], color='blue', label='Data Points')
plt.plot(df['Accident severity'], y_pred, color='red', label='Regression Line')
plt.xlabel('Accident severity')
plt.ylabel('Vehicle spped')
plt.legend()
plt.show()